language: python
python:
- '2.7'
before_install:
- pip install awscli
- "./travis-install-apex.sh"
install:
- "./install-requirements.sh"
- pip install coveralls
script: coverage run test-setup.py test
after_success:
- coveralls
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: inKeNAieHQ/sKJWYMNPWhpbE1JabMHRFepQo+a+Hb+U7bsmq6h2NB7akd3uPDwfjSqJa1Nk45F4NAS93/4mxwhtA1JHKgMIuaYtaVz5zvBrMKUBeT+NOU/05BMmbyxUt27+m8ZMLy1qc8iU1s0Lg2UJdBaF8D3MgiflV/yI3hvn3uYBXBToJFM2hywridlWEHmWkhJXGxKG1qG07BDrwlVgmCQYZ5MY4BbxQxmrWuFpJLe4z4yOC3kZeV7zI0/5oCkQTjQjylBO/xg4+m3CGphVdzDA6ilCl1Nb7oHe7WnDfkENlti7o34gQ+JghlOsu0As9ia27U+KuOHMGacrp9bx05twj1+AfRFo2oA7+5Y/iZXuUVBIaDXeWrYV5dZ6oc2y39puwbJd0BKvRuKzx88pV3eoCBZZ9QKPE7ykDPdFDgwNg4YqbklTk67WoMiUxl9ABzrjLotcl+g+AfDhQBUPeRtJ2fPNypqTgMnHM4oBJO3Zc+p3vIOuHCJww6rIa0MGUwrsFCbLtqCi59uds1+k7YkVhT6WdNTEdo7M1JA9DAXDJoC6I9N8/qwYShwpZxL038uJ2r2Hwl87nV4KmJEHjWUdnCfsUme5t4hG4ldYFjJYIfdYr4vw0fCErIBf2tBvvTdiwJQoDgMDMoHDyEDBq2wLm/nZqkEf9cDIwdrY=
  - AWS_REGION=us-west-2
