language: python
python:
- '2.7'
before_install:
- pip install awscli
- "./travis-install-apex.sh"
install:
- "./install-requirements.sh"
- pip install coveralls
script: coverage run test-setup.py test
after_success:
- coveralls
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
    secure: "Pf9fpLGI6ko70CKp9F77xuV2LskSCHCh94M9Q+zYLZKueCYzR68ahva1iUwX4YyEk/vknvcVqBuRA/WpDKe4JISJ+zmI+YcVjE+ItdOmYVNtBb9hAzloazGJcwOT+in9Hl/6u3pX+pb1rAQVWAgMZGnJj7Rea9EZKlxK7bwymBKw4lnWg35lCKy09uUKg47o2fqZpmYqsoXWvJoYT/W1IXEXT+yKYN3umd5QI1tHL4oEvg53ebDh/f+sxQgCLKf7DXmhUU4LJssN1FA7HK2Mtev0FTLNy6KhncQXOL/3txsyQH9BHIUmEW0THnnxVVJpb5Mo+1KtWpAtYoGIekpbJfvmUhalIo9CfX/K8DF+MbX/GG1xSadUpmNxMUZVromXtflS0WbHjFOBXIPyUtk4uqfm8uUTuEbbxzi+r7xd+C8sU6uPx2+Iq9bDK+oZimyL6UnmPqYGhs5vpgRe7NTMkYL7nGIpJK9FgVLPTtG4Nv4utyPVlJ5ZtjMdyJ2IlvTtEC6mnbRBrdNs3sgPvwBJqJjVEAl/x2x+0O8O7CG772d3Krtw2fJTsMmQoYhZcazVVZfpiv7ughaYfx+anwaPPKpThweItfwL3JAMR9kRSJAsbEy7Tu6bZUZmKIUFuTwXZMk6mg8vxvBL/jbG5qNZjIIw3BfiwQTyaUY0qsV5ru4="
