language: python
python:
  - '2.7'

before_install:
  - pip install awscli
  - "./travis-install-apex.sh"

install:
  - "./install-requirements.sh"
  - pip install coveralls

script: coverage run test-setup.py test

after_success:
  - coveralls
  - "./deploy.sh"

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true

deploy:
  provider: s3
  access_key_id: AKIAIWQUWIBNCSQGYGNQ
  secret_access_key:
    secure: d4wvKc4KohIQx02dPLR04S+uGpInYpU5V3eYHnhiUnocfcbMhiWlf2DEZLrfwPWMV/Rm2NsvNebqBwSBy2bvW3eyl5HjW2u+Sndfj5MN9HxhIpKbnpae9DiaAn8H8dcM2v+0ylQepd9h+dphmu/WrhT8FBUCIG0rHOjT/HNnZoXdcRTRO8TepScIJXf1jGNf+64x28aiKTnKSJN77mLjMZttVcKwlYwm9A30dfbSW9H0X578mAVE7n6OdcOXwAL5WRb4kJ95HsmO0WjoittkmEWmnkkatd4jPoYgHrwC74pUDlkWEr01vpRINoJ3DHy1BzxqeUcK/xObDCMCqDfFkZJDUPwYMeQ2LqolntpF18RQkXMnrEXIEyKWwR7QpwXZuphntnlAuSONHOJefdZJzJV5ecTCGH4BKzeVw3tgjcIS5G5UpW9u9cGa34krS3LCc7OMpLg9xPrRXHZz/b3iMXVg451q4BuP/LhSdPTD77Ss/eWr2JDhnPT3OD/Hkn45lombsaz5JVpNr3be3S7tmd9BzJEDbJ3v2k42BKMUtNpS+0UvENV9KLHCDM6/hWEwji7nU2WMbNrAELESJDF8HkS6W1AtfzscIMyVKY2rTUnhTwNLEOffzbI9xQxEIqzX7t/hT5fh/HMFlNcdS12GiS12wLYmvXmtG/t8Di+nzZk=
  bucket: S3 Bucket
