language: python
python:
- '2.7'
before_install:
- pip install awscli
- "./travis-install-apex.sh"
install:
- "./install-requirements.sh"
- pip install coveralls
script: coverage run test-setup.py test
after_success:
- coveralls
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
env:
  global:
  - AWS_REGION=us-west-2
  - secure: ELvi502H1e6STT2AzWRqM2HUv8FDMzQGC2UA9LNANL5XTlVOHhRXAIhfM3szR3l6VJs9+/QyQ7p/QgE+6jXP9MLqfkG/T1aClzckypGuAGefPvReHOji/znYCaJNljLTPLIeERweLRS5SyorjnHguEW/Tyc/ffRDZKH/xz19Xq9yLtaciEUEpD7HjbjNze7Mz6X05mtMO37RmMcBrqprq8Y5PAMTSCtQ7O/jpzregFvzBuqPI+BKVJ87lutXa9GHg/tfDZo5337nF8kXg3kabWW0a1ldZk7F4DonpTrB3GNuqCN1GkUibQ7AWBuDCsBLkkNQqzapcifJCoTZvh5SdgW5J7u/3xpbO0rGBnjhc7CpJ0hSASCOZXetaaJAJv4eaH426ZyRftl5TnDlKmvcIQUqp9WQqdZMQvBB7+tDqnTr+StT6yvou93FarRy3RoivuvIYG6b75qqqFGd/I03VVMg/iq8DcA8JFckVEAfUjbwTGXj4Vey81a7CIlVENHHREn28inIjsBuGjHtGLSkmgvtMEvBHv4jZDYeBUb9tl7cB2bd6QYpekVMyGpg4O8uG+hMS4v8gihl2GAQfQjylYuUQ24UChuElU1jFV0jWp66j5nte10TlVh2G6lWeYDwAFL4gFlIZRHpb6MwXSjXNhlIFpaE/7cp0wsE46K6KGI=
