language: python
python:
- '2.7'
before_install:
- pip install awscli
- "./travis-install-apex.sh"
install:
- "./install-requirements.sh"
- pip install coveralls
script: coverage run test-setup.py test
after_success:
- coveralls
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: bnjpGgSsFWYTtrKo4u0jmNUk2IZd2aUbEd/tISRPLUsapN6LwoGADlsZs0MXfu0iFu0LtVTXkXNctG1WpgKykwP30IkHeP2Wke1qQcVmHYCHD76ne3JJN8prClxyL6ZdTLE54WDdC7ZqS/oN7wDjT0zMvfTrAggEB/klA7fTyxLxGznZAyTxR1io2vInYsShn73aiQnIPHDLe9DZmaLWED1oEvuYh14k4r3iJAET2Y7z/Ec4xOanNna06CxDlwNy5GPsS/J+Kuws9fZc9e+LtRQpw0krVz7rCxAdim5vN4Ne7jE+8eL7OU7dmtOpqy/7VcNK01/y8mJx61n2j2BXf3z1zMkzvh3I75uTVjgQ4eJsL4BnXKdgPRYgLW1qv10+xIHf3U7R+5XDUJb7P+SQX/xNxjsE3p3JxyrM0mQbf3eZs7mzr3fZ0bnZ8KVsYp+Z9uL0MjEiQeqC8wKw8yLrTAJnSZQ4XFCG952Tss6pewXIW0qmV5n4VfZkhiSX70yAJfhVjESuDXqTWegaCSnYCZpm3LoaCUcvdoi+6qDMVOqJZVPGfsIKJxtOA5xDAy7j/0lDcXNiIpWyUwdfzogUkJRtpLZgKswtXnS1Y2j9DSy89ZtB1uNKi6GW6g9rzjD7bZuRLvyCKuomsive3Bz2FN75NVNh2n5lwOCS5NZBAgA=
  - AWS_REGION=us-west-2
