language: python
python:
- '2.7'
before_install:
- pip install awscli
- "./travis-install-apex.sh"
install:
- "./install-requirements.sh"
- pip install coveralls
script: coverage run test-setup.py test
after_success:
- coveralls
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: s8+dTzAW1E7wwMS9n3fG1wBnUQIEUxbkb9Yl19sl8FenViVOBWMiMpG5ZL6OsRjXn5Ju2IIMcaeCLKaVavbJ6B6oJB3aQesNkcfnIdXnLSyuILAg0eEwhPcxfrjXD7xhqmraoGX/e63j5LPH8KG/syYaQWCGdyWG+h2QsQ+AYgM+4WR8q1EM/gzCMfcGHqts2smm+DgP9Rz5+ZWmSB57GlhVUcnqfHNAvJB9MQ4aZQFjV35eOCyOKq+VcZVctCuC+Tj/ICsvaUmCswVkypgsVJxQIb2Q/ZJRQrIyCzZFuaqQB6iS4rmWQ/QQ1ctkNdsujSfbpaPffLtClqFklY48mG7zLDO+5UGFwdjzQs4J6iMpM9Y7coNMhlZ3M4DXy5o5JxI6OSA8WKEPvXx8iSGQ+k+PtELnao0YKnNSRRcU1C72gOFxb0QVJPrjjZzXl6EHANXg2NkuSgzk3vhR1paO12FbOszeH491CJ3JrtDA2MWBqYG44QqCcuFRwhQGr98L0ErnZfpNDfIwrQD8/jsc0xr4OH4vfP5xLWMjrAheQPKr/Slnp0JtlQLeWa6oP0O8PF4yh9MNpWUoau2DuR3kG4IwlJRznohSGpH8BL54VUOaUoJtpp8bFaQfvdio2x7NFq9MeJOurLn+NYpqCykiaQosFI2CWRlZU+6iyxSwJPQ=
  - AWS_REGION=us-west-2
